# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_hstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', django.contrib.postgres.fields.jsonb.JSONField(default={'class': 'IntegerField', 'kwargs': {'default': 0}, 'name': 'field'})),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', django_hstore.fields.DictionaryField()),
            ],
        ),
    ]
